"""Write `fixtures/model_reference.json` — the on-device inference contract.

The feature fixture proves the Kotlin extractor computes the same FEATURES as Python. It
says nothing about whether the app's ONNX Runtime produces the same PREDICTION as the
PyTorch model that was trained. This file closes that gap: it records, for the same
synthetic cases, the standardized model inputs and the PyTorch output, so the Android
instrumented test can assert its own ORT output matches to 1e-5.

Small, synthetic, and derived from committed fixture inputs — safe to commit (unlike the
model binary itself, which stays gitignored).
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import onnxruntime as ort
import torch

REPO = Path(__file__).resolve().parents[3]
FIXTURE = REPO / "fixtures" / "synthetic_trace.json"
OUT = REPO / "fixtures" / "model_reference.json"


def _sequence_inputs(case: dict, dyn_features, static_features):
    """Build the (7, d_dyn) + (d_static,) RAW inputs for one fixture case, exactly as the
    Kotlin `SequenceFeatures` does — same window, same daily slicing, same NaN handling."""
    import datetime as dt

    import pandas as pd

    from features import screenlock_features
    from features.spec_constants import TIMEZONE, WINDOW_DAYS

    label = dt.date.fromisoformat(case["label_date"])
    intervals = case["locked_intervals"]
    arr = (np.array(intervals, dtype="int64") if intervals
           else np.empty((0, 2), dtype="int64"))
    calls = np.array(case["calls"], dtype="int64")
    sms = np.array(case["sms"], dtype="int64")

    seq = []
    for k in range(WINDOW_DAYS):
        day = label - dt.timedelta(days=WINDOW_DAYS - k)
        a = pd.Timestamp(day, tz=TIMEZONE)
        d0, d1 = int(a.timestamp()), int((a + pd.Timedelta(days=1)).timestamp())
        sl = screenlock_features.screenlock_window_features(arr, d0, d1)
        seq.append([
            sl["unlock_count_per_day_mean"], sl["session_count_per_day_mean"],
            sl["session_duration_median"], sl["screen_on_fraction"],
            sl["nighttime_use_fraction_fixed"],
            float(((calls >= d0) & (calls < d1)).sum()),
            float(((sms >= d0) & (sms < d1)).sum()),
            1.0 if sl["days_with_data"] >= 1 else 0.0,
        ])

    static = [case["expected_features"][name] for name in static_features]
    static = [np.nan if v is None else float(v) for v in static]
    return np.array(seq, dtype="float64"), np.array(static, dtype="float64")


def write_model_reference(model, scaler, onnx_path: str, spec_version: str,
                          dyn_features, static_features) -> dict:
    trace = json.loads(FIXTURE.read_text(encoding="utf-8"))
    dm, ds, sm, ss = (np.asarray(x, dtype="float64") for x in scaler)

    model.eval()
    sess = ort.InferenceSession(onnx_path)

    cases, diffs = [], []
    for case in trace["cases"]:
        raw_seq, raw_static = _sequence_inputs(case, dyn_features, static_features)
        # Standardize FIRST, then NaN → 0 (which therefore means "the training mean").
        std_seq = np.nan_to_num((raw_seq - dm) / ds, nan=0.0).astype("float32")
        std_static = np.nan_to_num((raw_static - sm) / ss, nan=0.0).astype("float32")

        batch_seq = std_seq[None, :, :]
        batch_static = std_static[None, :]
        with torch.no_grad():
            torch_out = float(model(torch.tensor(batch_seq), torch.tensor(batch_static))
                              .numpy().reshape(-1)[0])
        ort_out = float(sess.run(None, {"seq": batch_seq, "static": batch_static})[0]
                        .reshape(-1)[0])
        diffs.append(abs(torch_out - ort_out))

        cases.append({
            "name": case["name"],
            "label_date": case["label_date"],
            # RAW inputs: what the Kotlin feature layer must produce (NaN → null).
            "raw_seq": [[None if np.isnan(v) else float(v) for v in row] for row in raw_seq],
            "raw_static": [None if np.isnan(v) else float(v) for v in raw_static],
            # STANDARDIZED inputs: what actually enters the model, so a mismatch localises
            # to either the scaler or the model rather than "somewhere in inference".
            "std_seq": [[float(v) for v in row] for row in std_seq],
            "std_static": [float(v) for v in std_static],
            "expected_stress": torch_out,
            "onnxruntime_stress": ort_out,
        })

    payload = {
        "spec_version": spec_version,
        "description": (
            "On-device inference contract. `expected_stress` is the PYTORCH output for the "
            "standardized inputs of each fixture case; the Android instrumented test loads "
            "the ONNX model, feeds the same inputs, and must match within `tolerance`. "
            "Generated by ml/src/training/run_dl.py — regenerate whenever the model or "
            "SPEC_VERSION changes."
        ),
        "onnx_file": Path(onnx_path).name,
        "tolerance": 1e-5,
        "dyn_features": list(dyn_features),
        "static_features": list(static_features),
        "standardization": {
            "dyn_mean": [float(x) for x in dm], "dyn_sd": [float(x) for x in ds],
            "static_mean": [float(x) for x in sm], "static_sd": [float(x) for x in ss],
            "order": "standardize_then_nan_to_zero",
        },
        "cases": cases,
    }
    OUT.write_text(json.dumps(payload, indent=2, allow_nan=False) + "\n", encoding="utf-8")

    max_diff = float(max(diffs)) if diffs else 0.0
    return {"path": str(OUT), "n_cases": len(cases), "max_abs_diff": max_diff,
            "match": max_diff <= 1e-5}
